### ISSUE TITLE
"error :Filesize exceed" with -dsk

### ISSUE THREAD

**Issue by VFD** [jeromelesaux/martine#1]
Hi.

Here a issue I saw when I try your program.
v0.26.0

"""
Error while insert (egx_bwind\mode0\BWINND.TXT) in dsk (egx_bwind\mode0\BWINND-OVERSCAN.DSK) error :Filesize exceed
"""

This happen each time I use the -dsk option.

Windows 10, build 2004

**Comment by jeromelesaux** [comment]
it's a warning, and the txt file is always larger than 64ko. If you want to add it in a dsk, it's better to import the txt file in an empty dsk.
