### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by ByteProject** [jeromelesaux/martine#12]
Not an issue but actually a feature request. I am the author of the Puny Buildtools (https://github.com/ByteProject/Puny-BuildTools), a build suite for authors of retro adventure games. It creates ready to run disk images for more than 30 supported retro systems, including the CPC. I am planning to incorporate martine in the build process for CPC, so that users can easily create loading screens.

What would be perfect, if martine has an option for the user to add custom lines at the end of the .BAS file it creates, so that one can add stuff like waiting for a keypress and loading the game binary.  I don't need many lines but two would be perfect.

**Comment by jeromelesaux** [comment]
Hello, I would be graceful to include your request in martine.
Custom lines means a lot of changes (a basic compiler to check the included lines syntax, add the checksum at the end of the basic line and change the key words in token).
Martine generate two types of basic script launcher (one for the classical screen 17ko and one for the overscan screen 33ko). You would like to custom the launcher in both ? 
If it's your choice, I need time to code the basic compiler and include it in martine.

**Comment by jeromelesaux** [comment]
I see also you're using idsk (a tool I coded several years ago). I suggest to use a new implementation https://github.com/jeromelesaux/dsk, this tool is still in development, the reverse of idsk which I discontinued.

**Comment by ByteProject** [comment]
That's great news! I would need the custom launcher only in the 17k version. Wow, I didn't know that you are the person who created idsk! Yes, I am using it for the ZX Spectrum and the CPC disk images. Will definitely look into your new tool! Thanks a lot :)

**Comment by ByteProject** [comment]
I closed this now since it is not really an issue. Feel free to ping me once you have the new version ready, so I can test it. Currently I am doing a workaround to automate the build process of CPC using Martine. I am using the loader as martine creates it, and then I add a second loader on disk and the game is then launched via chain merge command. Works, but of course having the option to manually provide additional Basic lines is much better :)
