### ISSUE TITLE
Fichier image source corrompue lors de la conversion / Avec option Noheader et Fullscreen

### ISSUE THREAD

**Issue by NolanMars** [jeromelesaux/martine#13]
Hello

Lorsque je lance une conversion avec les options "-mode0", "-noheader", "-fullscreen" , le fichier image source est corrompue et impossible de l'afficher :(

Quand je lance une conversion sans le -noheader, le fichier reste OK par contre.

**Comment by jeromelesaux** [comment]
Bonjour
Pourrais je avoir la totalité de la ligne de commande ? Utilisez vous l’option -out ?

**Comment by NolanMars** [comment]
Ou j'utilise l'option -out. Voici la ligne de commande complète : 
martine.exe -in * -mode 0 -noheader -fullscreen -out *

Sans la commande noheader, le fichier source n'est pas altéré.

Au cas ou, pour etre totalement exhaustif, j'utilise martine via un task sous vscode.

voici la task : 

{
            "label": "Image Conversion Mode 0",
            "type": "process",
            "group": {
                "kind": "build"
            },
            "command": "..\\Amstrad CPC\\Outils\\martine.exe",
            "args": [
                "-in",
                "${file}",
                "-mode",
                "0",
                "-noheader",
                "-fullscreen",
                "-out",
                "${relativeFileDirname}"
            ]
        }

Je ne pense pas que cela est la cause de n'anomalie, mais au cas ou...

**Comment by jeromelesaux** [comment]
L’option out est faite pour écrire les résultats dans un répertoire. 
pour éviter d’écraser des fichiers. 
en utilisant l’option -out repertoire_résultats l’application n’écrasera rien. Et l’étoile dans l’option -out ne sera près comprise par l’application.

**Comment by jeromelesaux** [comment]
Donc vous pouvez faire -out results. L’application créera un répertoire results et  sauvegardera tout dans ce répertoire.  Cependant je vais regarder l’écrasement de fichier avec les options que vous utilisez.

**Comment by NolanMars** [comment]
merci :)
J'ai effectué à nouveau le test avec la ligne de commande suivante, je confirme pour l'écrasement du fichier image en utilisant la ligne de commande : 

martine -in image.png -mode 0 -noheader -fullscreen -out results

Les fichiers sont bien crées à l'intérieur du répertoire results, par contre l'image d'origine se retrouve altérée.

Ce qui n'arrive pas si je n'utilise pas l'option -fullscreen

**Comment by jeromelesaux** [comment]
J’ai pas encore eut le temps de faire le test chez moi mais qu’elle est la version de Martine que vous utilisez ?

**Comment by NolanMars** [comment]
le dernier build dispo sur github, soit la v0.39

**Comment by jeromelesaux** [comment]
Je confirme le bug, je corrige ça tout de suite.

**Comment by jeromelesaux** [comment]
bug corrigé et je prévois une version très rapidement.

**Comment by jeromelesaux** [comment]
vous pouvez trouver la version corrigée ici https://github.com/jeromelesaux/martine/releases/download/v0.40/martine-i386-windows-0.40.zip

**Comment by NolanMars** [comment]
ca marche de mon coté ! merci
