### ISSUE TITLE
Feature not implemented, check your syntax

### ISSUE THREAD

**Issue by VFD** [jeromelesaux/martine#2]
HI.

Problem with example for EGX.
v0.26.0

I try do do the EGX.
Step 1 ok
Step 2 ok
Step 3, nok

Copy / Paste in command line

"""
martine -egx1 -m 0 -i egx_bwind/mode0/BWINND.SCR -m 1 egx_bwind/mode1/BWINND.SCR -o egx_bwind/ -pal egx_bwind/mode0/BWINND.PAL -f -dsk

Informations :
Size:
Width (384) pixels
High (272) pixels
Number of lines (272)
Number of columns (96)
Colors available in this mode (4)
Filename :BWINND.SCR, extension:.SCR
Error while applying on one image :Feature not implemented, check your syntax.
"""

Windows 10, build 2004.

**Comment by jeromelesaux** [comment]
To distinct the set of the two modes, you need to add -m2 option, your command line looks like : 

martine -egx1 -m 0 -i egx_bwind/mode0/BWINND.SCR -m2 1 egx_bwind/mode1/BWINND.SCR -o egx_bwind/ -pal egx_bwind/mode0/BWINND.PAL -f -dsk

**Comment by VFD** [comment]
Ok, so your exemple in the documentation have the same error.
Need to change it.

**Comment by VFD** [comment]
OK, now I've to solve this :

"""
Error while opening file () error open : The system cannot find the file specified.
Error while applying on one image :open : The system cannot find the file specified.
"""
First image.

**Comment by jeromelesaux** [comment]
well, the Martine does not found the file, it depends on several things. 
May you test `dir egx_bwind/mode0/BWINND.SCR` to try if you can reach it ?

**Comment by jeromelesaux** [comment]
now the documentation is fixed.

**Comment by VFD** [comment]
For Windows, dir need \.
DIR work but need backslash.

I tried with files in the same directory. no path.

martine -egx1 -m 0 -i BWINND0.SCR -m2 1 BWINND1.SCR -o egx_bwind/ -pal BWINND.PAL -f -dsk

"""
Informations :
Size:
Width (192) pixels
High (272) pixels
Number of lines (272)
Number of columns (96)
Colors available in this mode (16)
Filename :BWINND0.SCR, extension:.SCR
Raw overscan length #8000
Error while opening file () error open : The system cannot find the file specified.
Error while applying on one image :open : The system cannot find the file specified.
"""
file () ?

windows>martine -egx1 -m 0 -i BWINND0.SCR -m2 1 BWINND1.SCR -o egx_bwind/ -pal BWINND.PAL -f -dsk

if no .PAL file in directory.

"""
Informations :
Size:
Width (192) pixels
High (272) pixels
Number of lines (272)
Number of columns (96)
Colors available in this mode (16)
Filename :BWINND0.SCR, extension:.SCR
Error while opening file (BWINND.PAL) error open BWINND.PAL: The system cannot find the file specified.
Error while reading palette file (BWINND.PAL) :open BWINND.PAL: The system cannot find the file specified.
"""

 file (BWINND.PAL)
Good, no .PAL file in the directory.

May be a potential PATH problem from path access for .SCR routine.

**Comment by jeromelesaux** [comment]
I have no windows os, and I tested Martine on linux / macOS / raspbian without issues with paths.
The path access is managed by the OS, so try to surround your relative paths by double quotes .
I will try to create a windows bat for example.

**Comment by VFD** [comment]
OK.
Found another missing "-i2"

martine -egx1 -m 0 -i egx_bwind\mode0\BWINND.SCR -m2 1 -i2 egx_bwind\mode1\BWINND.SCR -o egx_bwind\ -pal egx_bwind\mode0\BWINND.PAL -f -dsk

Et voilà.

**Comment by jeromelesaux** [comment]
documentation updated.
