### ISSUE TITLE
.bat need a line to wait a keypress on the dsk

### ISSUE THREAD

**Issue by VFD** [jeromelesaux/martine#3]
HI.

When create a SCR on DSK.

The .BAT file finish and the word Ready appear on the screen.
.bat need a line to wait a keypress.
Need to just add the line.

**Comment by jeromelesaux** [comment]
it's a next feature.

**Comment by VFD** [comment]
Good, need same thing with the overscan.
Testing on Caprice Forever.
After overscan showing, evrything locked.
Cold reset to continue.

**Comment by jeromelesaux** [comment]
I can, the display in overscan is handled by assembly code. 
The final purpose of this was to be edited on a real CPC with Impdraw.
